# Generated by Django 4.0.1 on 2022-03-08 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(to='accounts.Student'),
        ),
    ]
