# Generated by Django 4.0.1 on 2022-03-08 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='teacher_id',
        ),
    ]
