# Generated by Django 4.0.1 on 2022-03-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_student_student_id_remove_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='students',
            field=models.ManyToManyField(blank=True, to='accounts.Student'),
        ),
    ]
