# Generated by Django 4.0.1 on 2022-03-09 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_classroom_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='classes',
            field=models.ManyToManyField(to='accounts.Classroom'),
        ),
    ]
