# Generated by Django 4.0.1 on 2022-03-09 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_classroom_students_student_classes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classes',
            new_name='classrooms',
        ),
    ]
