# Generated by Django 4.0.1 on 2022-03-09 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_classes_student_classrooms'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='classrooms',
            new_name='classes',
        ),
    ]
