# Generated by Django 4.0.1 on 2022-03-19 18:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_workitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='date_assigned',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
