# Generated by Django 4.0.1 on 2022-03-20 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_workitem_date_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='date_assigned',
        ),
    ]
