# Generated by Django 4.0.1 on 2022-03-21 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserUpload',
        ),
    ]
