# Generated by Django 4.0.1 on 2022-03-23 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_userupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.userupload'),
        ),
    ]
