# Generated by Django 4.0.1 on 2022-03-23 22:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_workitem_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='workitem',
            name='time_assigned',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workitem',
            name='date_assigned',
            field=models.DateField(auto_now_add=True),
        ),
    ]
