# Generated by Django 4.0.1 on 2022-03-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_workitem_time_assigned_alter_workitem_date_assigned'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='classroom_description',
            field=models.CharField(default='classroom description goes here', max_length=300),
            preserve_default=False,
        ),
    ]
