# Generated by Django 4.0.1 on 2022-03-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_classroom_classroom_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='classtrail_bool',
            field=models.BooleanField(default=True),
        ),
    ]
