# Generated by Django 4.0.1 on 2022-03-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userupload_classtrail_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workitem',
            name='submission',
        ),
        migrations.AddField(
            model_name='userupload',
            name='submission',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.workitem'),
        ),
    ]
