# Generated by Django 4.0.1 on 2022-03-26 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_workitem_submission_userupload_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='date',
            field=models.DateField(),
        ),
    ]
