# Generated by Django 4.0.1 on 2022-03-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_userupload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='grade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='classtrail_bool',
            field=models.BooleanField(default=True, verbose_name='Add to ClassTrail'),
        ),
    ]
