# Generated by Django 4.0.1 on 2022-03-29 00:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_userupload_grade_alter_userupload_classtrail_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userupload',
            name='grade',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)]),
        ),
    ]
