# Generated by Django 4.0.1 on 2022-03-30 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_userupload_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userupload',
            name='picture',
            field=models.FileField(upload_to='media/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'dox', 'png', 'jpg', 'jpeg', 'docx'])]),
        ),
    ]
