# Generated by Django 4.0.1 on 2022-04-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_classroom_classroom_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workitem',
            name='work_description',
            field=models.TextField(),
        ),
    ]
