# Generated by Django 4.0.1 on 2022-04-04 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_workitem_work_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='userupload',
            name='time_assigned',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
